# npx sonar to run everytime 
# Required project properties
sonar.projectKey=Mern-project
sonar.host.url=http://localhost:9000
sonar.login=sqp_f14239bd29fba9d9a402e0f36984d76843a23ed3

# Optional but recommended
sonar.projectName=Mern-project
sonar.projectVersion=1.0

# Paths
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Language & encoding
sonar.sourceEncoding=UTF-8
